version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20              # Specifies Node.js 14 runtime for installation

  build:
    commands:
      - ls -l
      - echo "Packaging application..."
      - cd search-photos
      - ls -l        # Navigates to the `upload-photos` directory
      - zip -r ../search-photos.zip index.mjs   # Zips `index.js` and `AppSpec.yaml` and moves zip to the root
      - mv AppSpec.yaml ../

artifacts:
  files:
    - search-photos.zip
    - AppSpec.yaml